# Generated by Django 3.0.6 on 2021-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.FloatField(blank=True, verbose_name='مبلغ فاکتور'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='monthly_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='حق اشتراک ماهیانه'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='staff_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت هر کاربر'),
        ),
    ]
