# Generated by Django 3.0.6 on 2021-02-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210201_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ فاکتور'),
        ),
    ]
