# Generated by Django 3.0.6 on 2021-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210126_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount',
            field=models.IntegerField(blank=True, verbose_name='مبلغ فاکتور'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('PAID', 'پرداخت شده'), ('NOT_PAID', 'پرداخت نشده'), ('PENDING', 'در حال پرداخت'), ('EXPIRED', 'منقضی شده')], max_length=20, verbose_name='وضعیت'),
        ),
    ]
