# Generated by Django 3.0.6 on 2021-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210218_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ فاکتور'),
        ),
    ]
