# Generated by Django 3.0.6 on 2021-08-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_account_billing_street'),
        ('teams', '0001_initial'),
        ('common', '0003_auto_20210724_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('status', models.CharField(blank=True, choices=[('جدید', 'جدید'), ('در حال انجام', 'در حال انجام'), ('پایان یافته', 'پایان یافته')], max_length=50, null=True, verbose_name='وضعیت')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان ')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع ')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyproject', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='common.Enrolled', verbose_name='مدیر پروژه')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tags', to='accounts.Tags', verbose_name='تگ\u200cها')),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_teams', to='teams.Teams', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
            },
        ),
    ]
