# Generated by Django 3.0.6 on 2021-02-02 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210201_1854'),
        ('common', '0007_auto_20210202_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inovice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('invoice_number', models.CharField(max_length=25, verbose_name='شماره فاکتور')),
                ('status', models.CharField(choices=[('پیش\u200cفاکتور', 'پیش\u200cفاکتور'), ('فاکتور', 'فاکتور'), ('کنسل شده', 'کنسل شده')], max_length=50, verbose_name='وضعیت')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ فاکتور')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('done_on', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('tax', models.IntegerField(blank=True, null=True, verbose_name='مالیات')),
                ('total_amount', models.FloatField(blank=True, null=True, verbose_name='جمع مبلغ فاکتور')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_invoices', to='accounts.Account', verbose_name='نام مشتری')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyinvoice', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('teams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_teams', to='teams.Teams', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='Inovice_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('total_item_amount', models.FloatField(blank=True, null=True, verbose_name='مجموع')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Invoiceitem', to='invoice.Inovice', verbose_name='فاکتور')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_product', to='common.Product', verbose_name='آیتم فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
