# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20210330_1929'),
        ('deals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=25, verbose_name='شماره فاکتور')),
                ('status', models.CharField(blank=True, choices=[('پیش\u200cفاکتور', 'پیش\u200cفاکتور'), ('فاکتور', 'فاکتور'), ('کنسل شده', 'کنسل شده')], max_length=50, null=True, verbose_name='وضعیت')),
                ('paid_status', models.CharField(blank=True, choices=[('نقدی', 'نقدی'), ('اعتباری', 'اعتباری'), ('غیر نقدی', 'غیر نقدی'), ('چک', 'چک')], max_length=50, null=True, verbose_name='نحوه پرداخت')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاریخ تنظیم')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('tax', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name=' درصد مالیات')),
                ('bargain', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='درصد تخفیف')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, verbose_name='جمع مبلغ فاکتور')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار ')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('total_bargain', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name=' مبلغ تخفیف')),
                ('total_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name=' مبلغ مالیات')),
                ('final_total_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='جمع نهایی مبلغ فاکتور')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_account', to='accounts.Account', verbose_name='نام مشتری')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyinvoice', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_deal', to='deals.Deal', verbose_name='معامله')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='تعداد')),
                ('total_item_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مجموع')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Invoiceitem', to='invoice.Invoice', verbose_name='فاکتور')),
                ('product_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_item_product', to='common.Product', verbose_name='آیتم فاکتور')),
            ],
            options={
                'verbose_name': 'آیتم فاکتور',
                'verbose_name_plural': 'آیتم\u200cهای فاکتور',
            },
        ),
    ]
