# Generated by Django 3.0.6 on 2021-02-02 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('common', '0008_auto_20210202_1900'),
        ('accounts', '0002_auto_20210201_1854'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inovice',
            new_name='Invoice',
        ),
    ]
