# Generated by Django 3.0.6 on 2021-02-16 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0012_auto_20210213_1529'),
        ('invoice', '0003_auto_20210207_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='done_on',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='teams',
        ),
        migrations.AddField(
            model_name='invoice',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='بایگانی شود؟'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bargain',
            field=models.IntegerField(blank=True, null=True, verbose_name='مالیات'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_deal', to='deals.Deal', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار '),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_account', to='accounts.Account', verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تنظیم'),
        ),
    ]
