# Generated by Django 3.0.6 on 2021-02-16 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210211_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0012_auto_20210213_1529'),
        ('invoice', '0004_auto_20210216_1049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inovice_item',
            new_name='Invoice_item',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bargain',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_deal', to='deals.Deal', verbose_name='معامله'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.IntegerField(blank=True, null=True, verbose_name=' درصد مالیات'),
        ),
    ]
