# Generated by Django 3.0.6 on 2021-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20210216_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='final_total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='جمع نهایی مبلغ فاکتور'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_bargain',
            field=models.FloatField(blank=True, null=True, verbose_name=' مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_tax',
            field=models.FloatField(blank=True, null=True, verbose_name=' مبلغ مالیات'),
        ),
    ]
