# Generated by Django 3.0.6 on 2021-02-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210216_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='final_total_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='جمع نهایی مبلغ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='جمع مبلغ فاکتور'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_bargain',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name=' مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_tax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name=' مبلغ مالیات'),
        ),
    ]
