# Generated by Django 3.0.6 on 2021-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20210216_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='total_item_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مجموع'),
        ),
    ]
