# Generated by Django 3.0.6 on 2021-02-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20210216_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bargain',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=20, null=True, verbose_name=' درصد مالیات'),
        ),
    ]
