# Generated by Django 3.0.6 on 2021-02-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20210216_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_status',
            field=models.CharField(blank=True, choices=[('نقدی', 'نقدی'), ('اعتباری', 'اعتباری'), ('غیر نقدی', 'غیر نقدی'), ('چک', 'چک')], max_length=50, null=True, verbose_name='نحوه پرداخت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('پیش\u200cفاکتور', 'پیش\u200cفاکتور'), ('فاکتور', 'فاکتور'), ('کنسل شده', 'کنسل شده')], max_length=50, null=True, verbose_name='وضعیت'),
        ),
    ]
