# Generated by Django 3.0.6 on 2021-02-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0016_auto_20210211_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0012_auto_20210213_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydealsreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_deal_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('pipeline_status', models.ManyToManyField(blank=True, null=True, related_name='reportpipeline', to='deals.Pipeline', verbose_name='مرحله فروش')),
                ('product', models.ManyToManyField(blank=True, null=True, related_name='reports_dealproducts', to='common.Product', verbose_name='محصول')),
            ],
        ),
    ]
