# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20210330_1929'),
        ('lead', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0001_initial'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('task_status', models.CharField(blank=True, choices=[('جدید', 'جدید'), ('در حال انجام', 'در حال انجام'), ('پایان یافته', 'پایان یافته')], max_length=50, null=True, verbose_name='وضعیت')),
                ('task_priority', models.CharField(blank=True, choices=[('پایین', 'پایین'), ('معمولی', 'معمولی'), ('بالا', 'بالا')], max_length=50, null=True, verbose_name='تقدم')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytaskreports', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('task_tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_tags', to='accounts.Tags', verbose_name='تگ\u200cهای فرصت\u200cها')),
                ('task_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_teams', to='teams.Teams', verbose_name='تیم\u200cها')),
            ],
            options={
                'verbose_name': 'گزارش وظایف',
                'verbose_name_plural': 'گزارشات وظایف',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Staffreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companystaffreports', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_staff', to='common.Enrolled', verbose_name='نام کارمند')),
            ],
            options={
                'verbose_name': 'گزارش کارمندان',
                'verbose_name_plural': 'گزارشات کارمندان',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Opportunityreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyopportunityreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('opportunity_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_source', to='opportunity.OpportunitySource', verbose_name='منبع فرصت\u200c')),
                ('opportunity_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_status', to='opportunity.OpportunityStatus', verbose_name='مرحله فرصت\u200c')),
                ('opportunity_tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_tags', to='accounts.Tags', verbose_name='تگ\u200cهای فرصت\u200cها')),
                ('opportunity_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_teams', to='teams.Teams', verbose_name='تیم\u200cها')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_opportunityproducts', to='common.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گزارش فرصت\u200cها',
                'verbose_name_plural': 'گزارشات فرصت\u200cها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Leadreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyleadsreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_source', to='lead.LeadSource', verbose_name='منبع سرنخ')),
                ('lead_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_status', to='lead.LeadStatus', verbose_name='مرحله سرنخ')),
                ('lead_tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_tags', to='accounts.Tags', verbose_name='تگ\u200cهای سرنخ\u200cها')),
                ('lead_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_teams', to='teams.Teams', verbose_name='تیم\u200cها')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_leadproducts', to='common.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گزارش سرنخ\u200cها',
                'verbose_name_plural': 'گزارشات سرنخ\u200cها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Dealreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydealsreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_deal_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('pipeline_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportpipeline', to='deals.Pipeline', verbose_name='مرحله فروش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_dealproducts', to='common.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': ' گزارش معاملات',
                'verbose_name_plural': 'گزارشات معاملات',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Companyreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycompanyreports', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'گزارش شرکت',
                'verbose_name_plural': 'گزارشات شرکت',
                'ordering': ['-created_on'],
            },
        ),
    ]
