# Generated by Django 3.0.6 on 2021-02-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_auto_20210213_1529'),
        ('common', '0016_auto_20210211_1554'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealreport',
            name='pipeline_status',
            field=models.ManyToManyField(blank=True, related_name='reportpipeline', to='deals.Pipeline', verbose_name='مرحله فروش'),
        ),
        migrations.AlterField(
            model_name='dealreport',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='reports_dealproducts', to='common.Product', verbose_name='محصول'),
        ),
    ]
