# Generated by Django 3.0.6 on 2021-02-15 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_account_archive'),
        ('common', '0016_auto_20210211_1554'),
        ('lead', '0005_lead_archive'),
        ('teams', '0002_teams_is_active'),
        ('reports', '0003_auto_20210214_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealreport',
            options={'ordering': ['-created_on'], 'verbose_name': ' گزارش معاملات', 'verbose_name_plural': 'گزارشات معاملات'},
        ),
        migrations.CreateModel(
            name='Leadreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyleadsreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('lead_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_source', to='lead.LeadSource', verbose_name='منبع سرنخ')),
                ('lead_tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_tags', to='accounts.Tags', verbose_name='تگ\u200cهای سرنخ\u200cها')),
                ('lead_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_teams', to='teams.Teams', verbose_name='تیم\u200cها')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_leadproducts', to='common.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گزارش سرنخ\u200cها',
                'verbose_name_plural': 'گزارشات سرنخ\u200cها',
                'ordering': ['-created_on'],
            },
        ),
    ]
