# Generated by Django 3.0.6 on 2021-02-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_lead_archive'),
        ('reports', '0004_auto_20210215_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadreport',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_source', to='lead.LeadSource', verbose_name='منبع سرنخ'),
        ),
        migrations.AlterField(
            model_name='leadreport',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_status', to='lead.LeadStatus', verbose_name='مرحله سرنخ'),
        ),
    ]
