# Generated by Django 3.0.6 on 2021-02-15 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210211_1554'),
        ('opportunity', '0005_auto_20210213_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_account_archive'),
        ('teams', '0002_teams_is_active'),
        ('reports', '0005_auto_20210215_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunityreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyopportunitysreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('opportunity_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_source', to='opportunity.OpportunitySource', verbose_name='منبع فرصت\u200c')),
                ('opportunity_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_status', to='opportunity.OpportunityStatus', verbose_name='مرحله فرصت\u200c')),
                ('opportunity_tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_tags', to='accounts.Tags', verbose_name='تگ\u200cهای فرصت\u200cها')),
                ('opportunity_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_teams', to='teams.Teams', verbose_name='تیم\u200cها')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_opportunityproducts', to='common.Product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گزارش فرصت\u200cها',
                'verbose_name_plural': 'گزارشات فرصت\u200cها',
                'ordering': ['-created_on'],
            },
        ),
    ]
