# Generated by Django 3.0.6 on 2021-02-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210211_1554'),
        ('reports', '0006_opportunityreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunityreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyopportunityreports', to='common.Company', verbose_name='شرکت'),
        ),
    ]
