# Generated by Django 3.0.6 on 2021-02-15 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0016_auto_20210211_1554'),
        ('teams', '0002_teams_is_active'),
        ('reports', '0007_auto_20210215_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('task_status', models.CharField(blank=True, choices=[('جدید', 'جدید'), ('در حال انجام', 'در حال انجام'), ('پایان یافته', 'پایان یافته')], max_length=50, null=True, verbose_name='وضعیت')),
                ('task_priority', models.CharField(blank=True, choices=[('پایین', 'پایین'), ('معمولی', 'معمولی'), ('بالا', 'بالا')], max_length=50, null=True, verbose_name='تقدم')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytaskreports', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('task_teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_teams', to='teams.Teams', verbose_name='تیم\u200cها')),
            ],
            options={
                'verbose_name': 'گزارش وظایف',
                'verbose_name_plural': 'گزارشات وظایف',
                'ordering': ['-created_on'],
            },
        ),
    ]
