# Generated by Django 3.0.6 on 2021-02-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_archive'),
        ('reports', '0008_taskreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskreport',
            old_name='converted_by',
            new_name='done_by',
        ),
        migrations.AddField(
            model_name='taskreport',
            name='task_tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_tags', to='accounts.Tags', verbose_name='تگ\u200cهای فرصت\u200cها'),
        ),
    ]
