# Generated by Django 3.0.6 on 2021-02-15 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20210211_1554'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0009_auto_20210215_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companystaffsreports', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_staff', to='common.Enrolled', verbose_name='مرحله سرنخ')),
            ],
            options={
                'verbose_name': 'گزارش کارمندان',
                'verbose_name_plural': 'گزارشات کارمندان',
                'ordering': ['-created_on'],
            },
        ),
    ]
