# Generated by Django 3.0.6 on 2021-02-16 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0016_auto_20210211_1554'),
        ('reports', '0010_staffreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffreport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companystaffreports', to='common.Company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='staffreport',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_staff', to='common.Enrolled', verbose_name='نام کارمند'),
        ),
        migrations.CreateModel(
            name='Companyreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('startdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('enddate', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycompanyreports', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_report_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'گزارش شرکت',
                'verbose_name_plural': 'گزارشات شرکت',
                'ordering': ['-created_on'],
            },
        ),
    ]
