# Generated by Django 3.0.6 on 2021-02-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20210218_2019'),
        ('reports', '0011_auto_20210216_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealreport',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_deal_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
        migrations.AlterField(
            model_name='leadreport',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_lead_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
        migrations.AlterField(
            model_name='opportunityreport',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_opportunity_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
        migrations.AlterField(
            model_name='taskreport',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_task_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
    ]
