# Generated by Django 3.0.6 on 2021-01-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'تیم', 'verbose_name_plural': 'تیم\u200cها'},
        ),
    ]
