# Generated by Django 3.0.6 on 2021-01-19 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210116_1353'),
        ('teams', '0002_auto_20210114_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyteams', to='common.Company', verbose_name='نام شرکت'),
        ),
    ]
