# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20210330_1929'),
        ('contacts', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadStatus_number', models.IntegerField(verbose_name='شماره مرحله')),
                ('LeadStatus_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('won', models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و تبدیل سرنخ به مشتری است این تیک را بزنید.')),
                ('lost', models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و شکست در تبدیل سرنخ است این تیک را بزنید.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyleadstatus', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_status_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'مرحله سرنخ',
                'verbose_name_plural': 'مراحل سرنخ',
            },
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadSource_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyleadsource', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_source_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'منبع سرنخ',
                'verbose_name_plural': 'منابع سرنخ',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='عنوان')),
                ('first_name', models.CharField(blank=True, max_length=64, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('closed_on', models.DateField(blank=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assigned_users', to='common.Enrolled', verbose_name='محول شده به')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyleads', to='common.Company', verbose_name='کاربر سایت')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contacts', to='contacts.Contact', verbose_name='اشخاص مرتبط')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lead_source', to='lead.LeadSource', verbose_name='منبع')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lead_status', to='lead.LeadStatus', verbose_name='مرحله سرنخ')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tags', verbose_name='تگ\u200cها')),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_teams', to='teams.Teams', verbose_name='تیم سرنخ')),
            ],
            options={
                'verbose_name': 'سرنخ',
                'verbose_name_plural': 'سرنخ\u200cها',
                'ordering': ['-created_on'],
            },
        ),
    ]
