# Generated by Django 3.0.6 on 2021-01-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_on'], 'verbose_name': 'سرنخ', 'verbose_name_plural': 'سرنخ\u200cها'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('assigned', 'محول\u200cشده'), ('in process', 'در\u200cحال \u200cانجام'), ('converted', 'تبدیل\u200cشده'), ('recycled', 'بازیافت\u200cشده'), ('closed', 'بسته\u200cشده')], max_length=255, null=True, verbose_name='وضعیت سرنخ'),
        ),
    ]
