# Generated by Django 3.0.6 on 2021-03-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='closed_on',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
    ]
