# Generated by Django 3.0.6 on 2021-02-10 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210207_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_teams_is_active'),
        ('contacts', '0003_auto_20210209_1308'),
        ('accounts', '0005_tags_company'),
        ('lead', '0002_auto_20210208_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assigned_users', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyleads', to='common.Company', verbose_name='کاربر سایت'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contacts', to='contacts.Contact', verbose_name='اشخاص مرتبط'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lead_source', to='lead.LeadSource', verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Lead_status', to='lead.LeadStatus', verbose_name='مرحله سرنخ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tags', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='teams',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_teams', to='teams.Teams', verbose_name='تیم سرنخ'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_source_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
    ]
