# Generated by Django 3.0.6 on 2021-02-10 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_auto_20210209_1308'),
        ('teams', '0002_teams_is_active'),
        ('lead', '0003_auto_20210210_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assigned_users', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contacts', to='contacts.Contact', verbose_name='اشخاص مرتبط'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_teams', to='teams.Teams', verbose_name='تیم سرنخ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='عنوان'),
        ),
    ]
