# Generated by Django 3.0.6 on 2021-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_auto_20210210_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='بایگانی شود؟'),
        ),
    ]
