# Generated by Django 3.0.6 on 2021-02-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20210218_2019'),
        ('lead', '0005_lead_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assigned_users', to='common.Enrolled', verbose_name='محول شده به'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
    ]
