# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام مشتری')),
                ('national_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد\u200c/شناسه ملی')),
                ('economic_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد اقتصادی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس موبایل')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس واتساپ')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس ثابت')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره فکس ')),
                ('industry', models.CharField(blank=True, choices=[('تبلیغات', 'تبلیغات'), ('کشاورزی', 'کشاورزی'), ('پوشاک و تجهیزات جانبی', 'پوشاک و تجهیزات جانبی'), ('خودرویی', 'خودرویی'), ('بانکی', 'بانکی'), ('بیوتکنولوژی', 'بیوتکنولوژی'), ('مصالح و ابزار ساختمانی', 'مصالح و ابزار ساختمانی'), ('شیمیایی', 'شیمیایی'), ('کامپیوتر', 'کامپیوتر'), ('آموزش', 'آموزش'), ('الکترونیک', 'الکترونیک'), ('انرژی', 'انرژی'), ('سرگرمی', 'سرگرمی'), ('مالی', 'مالی'), ('صنایع غذایی', 'صنایع غذایی'), ('خواربار', 'خواربار'), ('سلامت', 'سلامت'), ('بیمه', 'بیمه'), ('حقوقی', 'حقوقی'), ('مونتاژ و تولیدی', 'مونتاژ و تولیدی'), ('نشر و چاپ', 'نشر و چاپ'), ('املاک', 'املاک'), ('خدمات', 'خدمات'), ('نرم\u200cافزار', 'نرم\u200cافزار'), ('ورزش', 'ورزش'), ('تکنولوژی', 'تکنولوژی'), ('ارتباطات', 'ارتباطات'), ('تلوزیون', 'تلوزیون'), ('حمل و نقل', 'حمل و نقل'), ('سرمایه\u200cگذاری', 'سرمایه\u200cگذاری')], max_length=255, null=True, verbose_name='صنعت')),
                ('billing_address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('billing_street', models.CharField(blank=True, max_length=55, null=True, verbose_name='خیابان')),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر')),
                ('billing_state', models.CharField(blank=True, choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال بختیاری', 'چهارمحال بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهکیلویه و بویراحمد', 'کهکیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=200, null=True, verbose_name='استان')),
                ('billing_postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('billing_country', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('ترکیه', 'ترکیه'), ('چین', 'چین'), ('افغانستان', 'افغانستان'), ('عراق', 'عراق'), ('پاکستان', 'پاکستان'), ('آذربایجان', 'آذربایجان'), ('امارات', 'امارات'), ('سوریه', 'سوریه'), ('روسیه', 'روسیه'), ('قطر', 'قطر'), ('کویت', 'کویت'), ('ترکمنستان', 'ترکمنستان'), ('هندوستان', 'هندوستان')], max_length=200, null=True, verbose_name='کشور')),
                ('website', models.CharField(blank=True, max_length=200, null=True, verbose_name='وب\u200cسایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('success_measure', models.CharField(blank=True, max_length=255, null=True, verbose_name='مشتری موفقیت خود را بر چه اساسی تعیین می\u200cکند؟')),
                ('main_challenges', models.TextField(blank=True, null=True, verbose_name='مهمترین چالش\u200cهای مشتری چه چیز\u200cهایی هستند؟')),
                ('yearly_goal', models.TextField(blank=True, null=True, verbose_name='اهداف سالیانه مشتری چیست؟')),
                ('longterm_goal', models.TextField(blank=True, null=True, verbose_name='اهداف طولانی مدت مشتری چیست؟')),
                ('solution_expectation', models.TextField(blank=True, null=True, verbose_name='مشتری انتظار چه نوع راه\u200cحلی از شما دارد؟')),
                ('employee_count', models.CharField(blank=True, max_length=255, null=True, verbose_name='تعداد کارمندان مشتری')),
                ('yearly_revenue', models.CharField(blank=True, max_length=255, null=True, verbose_name='درآمد سالیانه مشتری در چه حدودی است؟')),
                ('customer_base', models.CharField(blank=True, max_length=255, null=True, verbose_name='مهمترین بخش\u200cبندی مشتریان شرکت چه کسانی هستند؟')),
                ('want_purchase', models.CharField(blank=True, max_length=255, null=True, verbose_name='چه دلیلی باعث خرید مشتری می\u200cشود؟')),
                ('solution_catalyst', models.TextField(blank=True, null=True, verbose_name='چه چیزی باعث ترغیب مشتری برای خرید چدید شده است؟')),
                ('competing_products', models.TextField(blank=True, null=True, verbose_name='مشتری چه محصولات دیگری را بررسی کرده است؟')),
                ('feature_convince', models.TextField(blank=True, null=True, verbose_name='کدام ویژگی محصول شما باعث ترغیب مشتری می\u200cشود؟')),
                ('competitors_feature', models.TextField(blank=True, null=True, verbose_name='کدام ویژگی رقبا باعث تاثیر\u200cگذاری بر روی مشتری می\u200cشود؟')),
                ('product_offer', models.TextField(blank=True, null=True, verbose_name='چه محصول اختصاصی مناسب مشتری است؟')),
                ('best_solution', models.TextField(blank=True, null=True, verbose_name='بهترین راه\u200cحل پیش\u200cروی مشتری کدام است؟')),
                ('business_help', models.TextField(blank=True, null=True, verbose_name='شرکت شما دقیقا چه کمکی می\u200cتواند به مشتری بکند؟')),
                ('active_socialnetworks', models.TextField(blank=True, null=True, verbose_name='مشتری در کدام شبکه\u200cهای اجتماعی فعال است؟')),
                ('active_groups', models.TextField(blank=True, null=True, verbose_name='مشتری در کدام گروه\u200cهای کاری فعال است؟')),
                ('information_source', models.TextField(blank=True, null=True, verbose_name='مشتری اطلاعات کاری خود را از چه طریقی تامین می\u200cکند؟')),
                ('count_decisionmakers', models.CharField(blank=True, max_length=255, null=True, verbose_name='چه تعداد تصمیم\u200cگیرنده برای مشتری وجود دارد؟')),
                ('influential_descisionmakers', models.TextField(blank=True, null=True, verbose_name='مهمترین تصمیم\u200cگیرنده مشتری چه کسی است؟')),
                ('stakeholders', models.TextField(blank=True, null=True, verbose_name='آیا ذینفعان دیگری برای مشتری وجود دارد؟')),
                ('influence_decisionmakers', models.TextField(blank=True, null=True, verbose_name='مهمترین فرد تاثیرگذار بر روی تصمیم\u200cگیرندگان چه کسی است؟')),
            ],
            options={
                'verbose_name': 'مشتری حقوقی',
                'verbose_name_plural': 'مشتریان حقوقی',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.TextField(null=True, verbose_name='موضوع ایمیل')),
                ('message_body', models.TextField(null=True, verbose_name='متن ایمیل')),
                ('timezone', models.CharField(default='UTC', max_length=100, verbose_name='منطقه زمانی')),
                ('scheduled_date_time', models.DateTimeField(null=True, verbose_name='زمان برنامه ریزی شده')),
                ('scheduled_later', models.BooleanField(default=False, verbose_name='بعدا ارسال شود')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('from_email', models.EmailField(max_length=254, verbose_name='از طریق ایمیل')),
                ('rendered_message_body', models.TextField(null=True, verbose_name='متن ایمیل رندر شده')),
            ],
            options={
                'verbose_name': 'ایمیل\u200c ارسالی /دریافتی',
                'verbose_name_plural': 'ایمیل\u200cهای ارسالی/دریافتی',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='وضعیت ارسال')),
            ],
            options={
                'verbose_name': 'لاگ ایمیل',
                'verbose_name_plural': 'لاگ\u200cهای ایمیل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
    ]
