# Generated by Django 3.0.6 on 2021-02-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام مشتری')),
                ('national_id', models.CharField(blank=True, max_length=64, verbose_name='کد\u200c/شناسه ملی')),
                ('economic_id', models.CharField(blank=True, max_length=64, verbose_name='کد اقتصادی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس موبایل')),
                ('office_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس ثابت')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='شماره فکس ')),
                ('industry', models.CharField(blank=True, choices=[('ADVERTISING', 'ADVERTISING'), ('AGRICULTURE', 'AGRICULTURE'), ('APPAREL & ACCESSORIES', 'APPAREL & ACCESSORIES'), ('AUTOMOTIVE', 'AUTOMOTIVE'), ('BANKING', 'BANKING'), ('BIOTECHNOLOGY', 'BIOTECHNOLOGY'), ('BUILDING MATERIALS & EQUIPMENT', 'BUILDING MATERIALS & EQUIPMENT'), ('CHEMICAL', 'CHEMICAL'), ('COMPUTER', 'COMPUTER'), ('EDUCATION', 'EDUCATION'), ('ELECTRONICS', 'ELECTRONICS'), ('ENERGY', 'ENERGY'), ('ENTERTAINMENT & LEISURE', 'ENTERTAINMENT & LEISURE'), ('FINANCE', 'FINANCE'), ('FOOD & BEVERAGE', 'FOOD & BEVERAGE'), ('GROCERY', 'GROCERY'), ('HEALTHCARE', 'HEALTHCARE'), ('INSURANCE', 'INSURANCE'), ('LEGAL', 'LEGAL'), ('MANUFACTURING', 'MANUFACTURING'), ('PUBLISHING', 'PUBLISHING'), ('REAL ESTATE', 'REAL ESTATE'), ('SERVICE', 'SERVICE'), ('SOFTWARE', 'SOFTWARE'), ('SPORTS', 'SPORTS'), ('TECHNOLOGY', 'TECHNOLOGY'), ('TELECOMMUNICATIONS', 'TELECOMMUNICATIONS'), ('TELEVISION', 'TELEVISION'), ('TRANSPORTATION', 'TRANSPORTATION'), ('VENTURE CAPITAL', 'VENTURE CAPITAL')], max_length=255, verbose_name='صنعت')),
                ('billing_address_line', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('billing_street', models.CharField(blank=True, max_length=55, verbose_name='خیابان')),
                ('billing_city', models.CharField(blank=True, max_length=255, verbose_name='شهر')),
                ('billing_postcode', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مشتری حقوقی',
                'verbose_name_plural': 'مشتریان حقوقی',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.TextField(null=True, verbose_name='موضوع ایمیل')),
                ('message_body', models.TextField(null=True, verbose_name='متن ایمیل')),
                ('timezone', models.CharField(default='UTC', max_length=100, verbose_name='منطقه زمانی')),
                ('scheduled_date_time', models.DateTimeField(null=True, verbose_name='زمان برنامه ریزی شده')),
                ('scheduled_later', models.BooleanField(default=False, verbose_name='بعدا ارسال شود')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('from_email', models.EmailField(max_length=254, verbose_name='از طریق ایمیل')),
                ('rendered_message_body', models.TextField(null=True, verbose_name='متن ایمیل رندر شده')),
            ],
            options={
                'verbose_name': 'ایمیل\u200c ارسالی /دریافتی',
                'verbose_name_plural': 'ایمیل\u200cهای ارسالی/دریافتی',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='وضعیت ارسال')),
            ],
            options={
                'verbose_name': 'لاگ ایمیل',
                'verbose_name_plural': 'لاگ\u200cهای ایمیل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
    ]
