# Generated by Django 3.0.6 on 2021-02-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthday'),
        ('common', '0013_auto_20210207_1343'),
        ('accounts', '0002_auto_20210201_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='billing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Country', verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='account',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_contacts', to='contacts.Contact', verbose_name='شخص مرتبط'),
        ),
    ]
