# Generated by Django 3.0.6 on 2021-04-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210330_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='billing_street',
        ),
    ]
