# Generated by Django 3.0.6 on 2021-01-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_on'], 'verbose_name': 'مشتری حقوقی', 'verbose_name_plural': 'مشتریان حقوقی'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'ایمیل\u200c ارسالی /دریافتی', 'verbose_name_plural': 'ایمیل\u200cهای ارسالی/دریافتی'},
        ),
        migrations.AlterModelOptions(
            name='emaillog',
            options={'verbose_name': 'لاگ ایمیل', 'verbose_name_plural': 'لاگ\u200cهای ایمیل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'تگ', 'verbose_name_plural': 'تگ\u200cها'},
        ),
    ]
