# Generated by Django 3.0.6 on 2021-02-10 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210207_1343'),
        ('accounts', '0004_auto_20210209_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytags', to='common.Company', verbose_name='تگ\u200cها'),
        ),
    ]
