# Generated by Django 3.0.6 on 2021-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tags_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='بایگانی شود؟'),
        ),
    ]
