# Generated by Django 3.0.6 on 2021-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210217_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contacts',
        ),
        migrations.AddField(
            model_name='account',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس واتساپ'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_street',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='account',
            name='economic_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='کد اقتصادی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره فکس '),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, choices=[('تبلیغات', 'ADVERTISING'), ('AGRICULTURE', 'AGRICULTURE'), ('APPAREL & ACCESSORIES', 'APPAREL & ACCESSORIES'), ('AUTOMOTIVE', 'AUTOMOTIVE'), ('BANKING', 'BANKING'), ('BIOTECHNOLOGY', 'BIOTECHNOLOGY'), ('BUILDING MATERIALS & EQUIPMENT', 'BUILDING MATERIALS & EQUIPMENT'), ('CHEMICAL', 'CHEMICAL'), ('COMPUTER', 'COMPUTER'), ('EDUCATION', 'EDUCATION'), ('ELECTRONICS', 'ELECTRONICS'), ('ENERGY', 'ENERGY'), ('ENTERTAINMENT & LEISURE', 'ENTERTAINMENT & LEISURE'), ('FINANCE', 'FINANCE'), ('FOOD & BEVERAGE', 'FOOD & BEVERAGE'), ('GROCERY', 'GROCERY'), ('HEALTHCARE', 'HEALTHCARE'), ('INSURANCE', 'INSURANCE'), ('LEGAL', 'LEGAL'), ('MANUFACTURING', 'MANUFACTURING'), ('PUBLISHING', 'PUBLISHING'), ('REAL ESTATE', 'REAL ESTATE'), ('SERVICE', 'SERVICE'), ('SOFTWARE', 'SOFTWARE'), ('SPORTS', 'SPORTS'), ('TECHNOLOGY', 'TECHNOLOGY'), ('TELECOMMUNICATIONS', 'TELECOMMUNICATIONS'), ('TELEVISION', 'TELEVISION'), ('TRANSPORTATION', 'TRANSPORTATION'), ('VENTURE CAPITAL', 'VENTURE CAPITAL')], max_length=255, null=True, verbose_name='صنعت'),
        ),
        migrations.AlterField(
            model_name='account',
            name='national_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='کد\u200c/شناسه ملی'),
        ),
        migrations.AlterField(
            model_name='account',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس ثابت'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس موبایل'),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='وب\u200cسایت'),
        ),
    ]
