# Generated by Django 3.0.6 on 2021-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210313_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active_groups',
            field=models.TextField(blank=True, null=True, verbose_name='مشتری در کدام گروه\u200cهای کاری فعال است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='active_socialnetworks',
            field=models.TextField(blank=True, null=True, verbose_name='مشتری در کدام شبکه\u200cهای اجتماعی فعال است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='best_solution',
            field=models.TextField(blank=True, null=True, verbose_name='بهترین راه\u200cحل پیش\u200cروی مشتری کدام است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='business_help',
            field=models.TextField(blank=True, null=True, verbose_name='شرکت شما دقیقا چه کمکی می\u200cتواند به مشتری بکند؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='competing_products',
            field=models.TextField(blank=True, null=True, verbose_name='مشتری چه محصولات دیگری را بررسی کرده است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='competitors_feature',
            field=models.TextField(blank=True, null=True, verbose_name='کدام ویژگی رقبا باعث تاثیر\u200cگذاری بر روی مشتری می\u200cشود؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='count_decisionmakers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='چه تعداد تصمیم\u200cگیرنده برای مشتری وجود دارد؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='customer_base',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مهمترین بخش\u200cبندی مشتریان شرکت چه کسانی هستند؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='employee_count',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تعداد کارمندان مشتری'),
        ),
        migrations.AddField(
            model_name='account',
            name='feature_convince',
            field=models.TextField(blank=True, null=True, verbose_name='کدام ویژگی محصول شما باعث ترغیب مشتری می\u200cشود؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='influence_decisionmakers',
            field=models.TextField(blank=True, null=True, verbose_name='مهمترین فرد تاثیرگذار بر روی تصمیم\u200cگیرندگان چه کسی است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='influential_descisionmakers',
            field=models.TextField(blank=True, null=True, verbose_name='مهمترین تصمیم\u200cگیرنده مشتری چه کسی است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='information_source',
            field=models.TextField(blank=True, null=True, verbose_name='مشتری اطلاعات کاری خود را از چه طریقی تامین می\u200cکند؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='longterm_goal',
            field=models.TextField(blank=True, null=True, verbose_name='اهداف طولانی مدت مشتری چیست؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='main_challenges',
            field=models.TextField(blank=True, null=True, verbose_name='مهمترین چالش\u200cهای مشتری چه چیز\u200cهایی هستند؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='product_offer',
            field=models.TextField(blank=True, null=True, verbose_name='چه محصول اختصاصی مناسب مشتری است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='solution_catalyst',
            field=models.TextField(blank=True, null=True, verbose_name='چه چیزی باعث ترغیب مشتری برای خرید چدید شده است؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='solution_expectation',
            field=models.TextField(blank=True, null=True, verbose_name='مشتری انتظار چه نوع راه\u200cحلی از شما دارد؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='stakeholders',
            field=models.TextField(blank=True, null=True, verbose_name='آیا ذینفعان دیگری برای مشتری وجود دارد؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='success_measure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مشتری موفقیت خود را بر چه اساسی تعیین می\u200cکند؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='want_purchase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='چه دلیلی باعث خرید مشتری می\u200cشود؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='yearly_goal',
            field=models.TextField(blank=True, null=True, verbose_name='اهداف سالیانه مشتری چیست؟'),
        ),
        migrations.AddField(
            model_name='account',
            name='yearly_revenue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='درآمد سالیانه مشتری در چه حدودی است؟'),
        ),
    ]
