# Generated by Django 3.0.6 on 2021-01-28 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_auto_20210119_1741'),
        ('common', '0004_company_access_date'),
        ('teams', '0003_auto_20210119_1741'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_number', models.IntegerField(verbose_name='شماره مرحله')),
                ('pipeline_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companypipelines', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipline_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'مرحله فروش',
                'verbose_name_plural': 'مراحل فروش',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام حساب')),
                ('deal_amount', models.FloatField(blank=True, null=True, verbose_name='مبلغ معامله')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('assigned_to', models.ManyToManyField(related_name='deal_assigned_users', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydeals', to='common.Company', verbose_name='شرکت')),
                ('contacts', models.ManyToManyField(related_name='deal_contacts', to='contacts.Contact', verbose_name='مشتریان سرنخ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('pipeline_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealpipeline', to='deals.Pipeline', verbose_name='مرحله فروش')),
                ('teams', models.ManyToManyField(related_name='deal_teams', to='teams.Teams', verbose_name='تیم سرنخ')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
                'ordering': ['-created_on'],
            },
        ),
    ]
