# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20210330_1929'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_number', models.IntegerField(verbose_name='ترتیب در فرایند')),
                ('pipeline_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('won', models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و فروش موفق است این تیک را بزنید.')),
                ('lost', models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و شکست در معامله است این تیک را بزنید.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companypipelines', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipline_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'مرحله فروش',
                'verbose_name_plural': 'مراحل فروش',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('account_name', models.CharField(blank=True, max_length=255, verbose_name='نام حساب')),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مبلغ معامله')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_acounts', to='accounts.Account', verbose_name='مشتری')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_assigned_users', to='common.Enrolled', verbose_name='محول شده به')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydeals', to='common.Company', verbose_name='شرکت')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('pipeline_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealpipeline', to='deals.Pipeline', verbose_name='مرحله فروش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealproducts', to='common.Product', verbose_name='محصول')),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_teams', to='teams.Teams', verbose_name='تیم معالمه')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
                'ordering': ['-created_on'],
            },
        ),
    ]
