# Generated by Django 3.0.6 on 2021-02-07 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teams_is_active'),
        ('deals', '0002_auto_20210207_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='teams',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_teams', to='teams.Teams', verbose_name='تیم معالمه'),
        ),
    ]
