# Generated by Django 3.0.6 on 2021-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20210207_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='closed_on',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
    ]
