# Generated by Django 3.0.6 on 2021-02-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20210201_1854'),
        ('teams', '0002_teams_is_active'),
        ('common', '0013_auto_20210207_1343'),
        ('deals', '0004_auto_20210207_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_acounts', to='accounts.Account', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_assigned_users', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydeals', to='common.Company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealproducts', to='common.Product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_teams', to='teams.Teams', verbose_name='تیم معالمه'),
        ),
    ]
