# Generated by Django 3.0.6 on 2021-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_auto_20210207_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='lost',
            field=models.BooleanField(default=False, verbose_name='در صروتی که این مرحله بیانگر مرحله پایانی و شکست در معامله است این تیک را بزنید'),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='won',
            field=models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و فروش موفق است این تیک را بزنید'),
        ),
    ]
