# Generated by Django 3.0.6 on 2021-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20210207_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_number',
            field=models.IntegerField(unique=True, verbose_name='شماره مرحله'),
        ),
    ]
