# Generated by Django 3.0.6 on 2021-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20210207_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='lost',
            field=models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و شکست در معامله است این تیک را بزنید.'),
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='won',
            field=models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و فروش موفق است این تیک را بزنید.'),
        ),
    ]
