# Generated by Django 3.0.6 on 2021-02-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_auto_20210207_2324'),
        ('deals', '0008_auto_20210208_1739'),
    ]

    operations = [
    ]
