# Generated by Django 3.0.6 on 2021-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_merge_20210209_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_number',
            field=models.IntegerField(verbose_name='شماره مرحله'),
        ),
    ]
