# Generated by Django 3.0.6 on 2021-02-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_deal_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مبلغ معامله'),
        ),
    ]
