# Generated by Django 3.0.6 on 2021-02-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_auto_20210217_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مبلغ معامله'),
        ),
    ]
