# Generated by Django 3.0.6 on 2021-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_auto_20210217_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='pipeline_number',
            field=models.IntegerField(verbose_name='ترتیب در فرایند'),
        ),
    ]
