# Generated by Django 3.0.6 on 2021-02-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20210218_2019'),
        ('deals', '0016_auto_20210218_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_assigned_users', to='common.Enrolled', verbose_name='محول شده به'),
        ),
    ]
