# Generated by Django 3.0.6 on 2021-02-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20210218_2019'),
        ('deals', '0017_auto_20210220_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
    ]
