# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس واتساپ')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره فکس ')),
                ('address', models.CharField(blank=True, max_length=350, null=True, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('billing_address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('billing_street', models.CharField(blank=True, max_length=55, null=True, verbose_name='خیابان')),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر')),
                ('billing_state', models.CharField(blank=True, choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال بختیاری', 'چهارمحال بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهکیلویه و بویراحمد', 'کهکیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=200, null=True, verbose_name='استان')),
                ('billing_postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('billing_country', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('ترکیه', 'ترکیه'), ('چین', 'چین'), ('افغانستان', 'افغانستان'), ('عراق', 'عراق'), ('پاکستان', 'پاکستان'), ('آذربایجان', 'آذربایجان'), ('امارات', 'امارات'), ('سوریه', 'سوریه'), ('روسیه', 'روسیه'), ('قطر', 'قطر'), ('کویت', 'کویت'), ('ترکمنستان', 'ترکمنستان'), ('هندوستان', 'هندوستان')], max_length=200, null=True, verbose_name='کشور')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_contacts', to='accounts.Account', verbose_name='مشتری مرتبط')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycontacts', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
    ]
