# Generated by Django 3.0.6 on 2021-02-01 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='موبایل')),
                ('office_phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن ثابت')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='شماره فکس ')),
                ('address', models.CharField(blank=True, max_length=350, verbose_name='آدرس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('billing_address_line', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('billing_street', models.CharField(blank=True, max_length=55, verbose_name='خیابان')),
                ('billing_city', models.CharField(blank=True, max_length=255, verbose_name='شهر')),
                ('billing_postcode', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('billing_country', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.Country', verbose_name='کشور')),
                ('billing_state', models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='common.Province', verbose_name='استان')),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='companycontacts', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
    ]
