# Generated by Django 3.0.6 on 2021-02-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210220_1204'),
        ('contacts', '0004_contact_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_contacts', to='accounts.Account', verbose_name='مشتری مرتبط'),
        ),
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس واتساپ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='billing_address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='billing_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='billing_postcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='billing_street',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره فکس '),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='موبایل'),
        ),
    ]
