# Generated by Django 3.0.6 on 2021-01-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_auto_20210114_1947'),
        ('common', '0003_auto_20210116_1353'),
        ('accounts', '0003_auto_20210116_1353'),
        ('contacts', '0002_auto_20210114_1947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('In Progress', 'در حال انجام'), ('Completed', 'پایان یافته')], max_length=50, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('Low', 'پایین'), ('Medium', 'معمولی'), ('High', 'بالا')], max_length=50, verbose_name='تقدم')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='مهلت انجام')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_tasks', to='accounts.Account', verbose_name='نام شرکت')),
                ('assigned_to', models.ManyToManyField(related_name='users_tasks', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Company', verbose_name='کاربر سایت')),
                ('contacts', models.ManyToManyField(related_name='contacts_tasks', to='contacts.Contact', verbose_name='نام مشتری')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('teams', models.ManyToManyField(related_name='tasks_teams', to='teams.Teams', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'کار',
                'verbose_name_plural': 'کارها',
                'ordering': ['-due_date'],
            },
        ),
    ]
