# Generated by Django 3.0.6 on 2021-04-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, choices=[('جلسه', 'جلسه'), ('تماس', 'تماس'), ('ایمیل', 'ایمیل'), ('پیش\u200cفاکتور', 'پیش\u200cفاکتور'), ('فاکتور', 'فاکتور'), ('پیگیری', 'پیگیری'), ('قرارداد', 'قرارداد'), ('کاتالوگ', 'کاتالوگ'), ('پروپوزال', 'پروپوزال')], max_length=50, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('پایین', 'پایین'), ('معمولی', 'معمولی'), ('بالا', 'بالا')], max_length=50, null=True, verbose_name='تقدم'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('جدید', 'جدید'), ('در حال انجام', 'در حال انجام'), ('پایان یافته', 'پایان یافته')], max_length=50, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
