# Generated by Django 3.0.6 on 2021-02-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210202_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_on',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
    ]
