# Generated by Django 3.0.6 on 2021-08-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_auto_20210724_1158'),
        ('tasks', '0003_auto_20210501_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(blank=True, choices=[('جلسه', 'جلسه'), ('تماس', 'تماس'), ('ایمیل', 'ایمیل'), ('پیش\u200cفاکتور', 'پیش\u200cفاکتور'), ('فاکتور', 'فاکتور'), ('پیگیری', 'پیگیری'), ('قرارداد', 'قرارداد'), ('کاتالوگ', 'کاتالوگ'), ('پروپوزال', 'پروپوزال'), ('سایر', 'سایر')], max_length=50, null=True, verbose_name='موضوع کار'),
        ),
        migrations.CreateModel(
            name='TaskSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasksubject_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companytasksubject', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasksubject_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'موضوع',
                'verbose_name_plural': 'موضوعات',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tasksubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasksubject', to='tasks.TaskSubject', verbose_name='موضوع'),
        ),
    ]
