# Generated by Django 3.0.6 on 2021-02-10 17:58

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210202_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='مهلت انجام'),
        ),
    ]
