# Generated by Django 3.0.6 on 2021-02-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teams_is_active'),
        ('tasks', '0008_auto_20210210_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='مهلت انجام'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_teams', to='teams.Teams', verbose_name='تیم'),
        ),
    ]
