# Generated by Django 3.0.6 on 2021-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210211_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='بایگانی شود؟'),
        ),
    ]
