# Generated by Django 3.0.6 on 2021-02-15 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_archive'),
        ('tasks', '0010_task_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tags', verbose_name='تگ\u200cها'),
        ),
    ]
