# Generated by Django 3.0.6 on 2021-02-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20210218_2019'),
        ('tasks', '0011_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_tasks', to='common.Enrolled', verbose_name='محول شده به'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_done_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط'),
        ),
    ]
