# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('role', models.CharField(choices=[('ADMIN', 'ادمین'), ('USER', 'کاربر')], max_length=50, verbose_name='نقش')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='media', verbose_name='تصویر کاربر')),
                ('has_sales_access', models.BooleanField(default=False, verbose_name='دسترسی به فروش')),
                ('has_marketing_access', models.BooleanField(default=False, verbose_name='دسترسی به بازاریابی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-is_active'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('street', models.CharField(blank=True, max_length=55, null=True, verbose_name='خیابان')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='استان')),
                ('postcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='کدپستی')),
                ('country', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('ترکیه', 'ترکیه'), ('چین', 'چین'), ('افغانستان', 'افغانستان'), ('عراق', 'عراق'), ('پاکستان', 'پاکستان'), ('آذربایجان', 'آذربایجان'), ('امارات', 'امارات'), ('سوریه', 'سوریه'), ('روسیه', 'روسیه'), ('قطر', 'قطر'), ('کویت', 'کویت'), ('ترکمنستان', 'ترکمنستان'), ('هندوستان', 'هندوستان')], max_length=200, null=True, verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='<لینک شرکت>/selikan.ir')),
                ('user_limit', models.IntegerField(blank=True, default=1, null=True, verbose_name='محدودیت کاربر')),
                ('country', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('ترکیه', 'ترکیه'), ('چین', 'چین'), ('افغانستان', 'افغانستان'), ('عراق', 'عراق'), ('پاکستان', 'پاکستان'), ('آذربایجان', 'آذربایجان'), ('امارات', 'امارات'), ('سوریه', 'سوریه'), ('روسیه', 'روسیه'), ('قطر', 'قطر'), ('کویت', 'کویت'), ('ترکمنستان', 'ترکمنستان'), ('هندوستان', 'هندوستان')], max_length=200, null=True, verbose_name='کشور')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('access_date', models.DateTimeField(verbose_name='تاریخ اعتبار حساب')),
                ('national_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد\u200c/شناسه ملی')),
                ('economic_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد اقتصادی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='شماره تماس موبایل')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس ثابت')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره فکس ')),
                ('industry', models.CharField(blank=True, choices=[('تبلیغات', 'تبلیغات'), ('کشاورزی', 'کشاورزی'), ('پوشاک و تجهیزات جانبی', 'پوشاک و تجهیزات جانبی'), ('خودرویی', 'خودرویی'), ('بانکی', 'بانکی'), ('بیوتکنولوژی', 'بیوتکنولوژی'), ('مصالح و ابزار ساختمانی', 'مصالح و ابزار ساختمانی'), ('شیمیایی', 'شیمیایی'), ('کامپیوتر', 'کامپیوتر'), ('آموزش', 'آموزش'), ('الکترونیک', 'الکترونیک'), ('انرژی', 'انرژی'), ('سرگرمی', 'سرگرمی'), ('مالی', 'مالی'), ('صنایع غذایی', 'صنایع غذایی'), ('خواربار', 'خواربار'), ('سلامت', 'سلامت'), ('بیمه', 'بیمه'), ('حقوقی', 'حقوقی'), ('مونتاژ و تولیدی', 'مونتاژ و تولیدی'), ('نشر و چاپ', 'نشر و چاپ'), ('املاک', 'املاک'), ('خدمات', 'خدمات'), ('نرم\u200cافزار', 'نرم\u200cافزار'), ('ورزش', 'ورزش'), ('تکنولوژی', 'تکنولوژی'), ('ارتباطات', 'ارتباطات'), ('تلوزیون', 'تلوزیون'), ('حمل و نقل', 'حمل و نقل'), ('سرمایه\u200cگذاری', 'سرمایه\u200cگذاری')], max_length=255, null=True, verbose_name='صنعت')),
                ('billing_address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس')),
                ('billing_street', models.CharField(blank=True, max_length=55, null=True, verbose_name='خیابان')),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='شهر')),
                ('billing_state', models.CharField(blank=True, choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال بختیاری', 'چهارمحال بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهکیلویه و بویراحمد', 'کهکیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=255, null=True, verbose_name='استان')),
                ('billing_postcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='وب\u200cسایت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='company', verbose_name='لوگو شرکت')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام استان')),
                ('short_name', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('ترکیه', 'ترکیه'), ('چین', 'چین'), ('افغانستان', 'افغانستان'), ('عراق', 'عراق'), ('پاکستان', 'پاکستان'), ('آذربایجان', 'آذربایجان'), ('امارات', 'امارات'), ('سوریه', 'سوریه'), ('روسیه', 'روسیه'), ('قطر', 'قطر'), ('کویت', 'کویت'), ('ترکمنستان', 'ترکمنستان'), ('هندوستان', 'هندوستان')], max_length=200, null=True, verbose_name='نام کوتاه استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام محصول')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد محصول')),
                ('unit', models.CharField(blank=True, choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('گرم', ' گرم'), ('تن', 'تن'), ('بسته', 'بسته'), ('جعبه', 'جعبه'), ('کارتن', 'کارتن'), ('متر', 'متر'), ('لیتر', 'لیتر'), ('مترمکعب', 'مترکعب'), ('سی\u200cسی', 'سی\u200cسی'), ('مثقال', 'مثقال')], max_length=255, null=True, verbose_name='واحد اندازه\u200cگیری')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت واحد محصول')),
                ('price_unit', models.CharField(blank=True, choices=[('تومان', 'تومان'), ('ریال', 'ریال'), ('دلار', ' دلار'), ('یورو', 'یورو'), ('پوند', 'پوند'), ('دینار', 'دینار'), ('درهم', 'درهم'), ('افغانی', 'افغانی'), ('لیر', 'لیر'), ('مانات', 'مانات')], max_length=255, null=True, verbose_name='واحد پولی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyproducts', to='common.Company', verbose_name='محصولات شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('previous_attempts', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_enroll', to='common.Company', verbose_name='نام شرکت')),
                ('staff', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
        migrations.CreateModel(
            name='Enroll_Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyinvitations', to='common.Company', verbose_name='نام شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده دعوت')),
            ],
            options={
                'verbose_name': 'کاربر دعوت شده',
                'verbose_name_plural': 'کاربران دعوت شده',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کشور')),
                ('short_name', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('ترکیه', 'ترکیه'), ('چین', 'چین'), ('افغانستان', 'افغانستان'), ('عراق', 'عراق'), ('پاکستان', 'پاکستان'), ('آذربایجان', 'آذربایجان'), ('امارات', 'امارات'), ('سوریه', 'سوریه'), ('روسیه', 'روسیه'), ('قطر', 'قطر'), ('کویت', 'کویت'), ('ترکمنستان', 'ترکمنستان'), ('هندوستان', 'هندوستان')], max_length=200, null=True, verbose_name='نام کوتاه کشور')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycountries', to='common.Company', verbose_name='کشورهای مرتبط شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده کشور')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشورها',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='companystaff', through='common.Enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
