# Generated by Django 3.0.6 on 2021-02-02 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 7, 50, 10, 273298, tzinfo=utc), verbose_name='تاریخ اعتبار حساب'),
        ),
    ]
