# Generated by Django 3.0.6 on 2021-01-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='لینک شرکت'),
            preserve_default=False,
        ),
    ]
