# Generated by Django 3.0.6 on 2021-04-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='user_limit',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='محدودیت کاربر'),
        ),
    ]
