# Generated by Django 3.0.6 on 2021-07-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210430_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
    ]
