# Generated by Django 3.0.6 on 2021-02-02 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210202_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 15, 27, 47, 757536, tzinfo=utc), verbose_name='تاریخ اعتبار حساب'),
        ),
    ]
