# Generated by Django 3.0.6 on 2021-02-07 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20210207_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 9, 37, 24, 936958, tzinfo=utc), verbose_name='تاریخ اعتبار حساب'),
        ),
    ]
