# Generated by Django 3.0.6 on 2021-02-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20210207_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='access_date',
            field=models.DateTimeField(verbose_name='تاریخ اعتبار حساب'),
        ),
    ]
