# Generated by Django 3.0.6 on 2021-02-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20210207_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='company',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='لوگو شرکت'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='تصویر کاربر'),
        ),
    ]
