# Generated by Django 3.0.6 on 2021-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20210211_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='companies_logos', verbose_name='لوگو شرکت'),
        ),
    ]
