# Generated by Django 3.0.6 on 2021-02-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20210211_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='thumbnail',
            new_name='logo',
        ),
    ]
