# Generated by Django 3.0.6 on 2021-02-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20210217_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='لوگو شرکت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='تصویر کاربر'),
        ),
    ]
