# Generated by Django 3.0.6 on 2021-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20210218_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='company', verbose_name='لوگو شرکت'),
        ),
    ]
