# Generated by Django 3.0.6 on 2021-02-18 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20210218_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='companystaff', through='common.Enrolled', to=settings.AUTH_USER_MODEL),
        ),
    ]
