# Generated by Django 3.0.6 on 2021-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20210218_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sub_domain',
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='وب\u200cسایت'),
        ),
    ]
