# Generated by Django 3.0.6 on 2021-02-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20210218_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_limit',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='محدودیت کاربر'),
        ),
    ]
