# Generated by Django 3.0.6 on 2021-02-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20210218_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='<لینک شرکت>/selikan.ir'),
        ),
    ]
