# Generated by Django 3.0.6 on 2021-02-20 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20210220_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyinvitations', to='common.Company', verbose_name='محصولات شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده دعوت')),
            ],
            options={
                'verbose_name': 'کاربر دعوت شده',
                'verbose_name_plural': 'کاربران دعوت شده',
            },
        ),
    ]
