# Generated by Django 3.0.6 on 2021-02-20 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_enroll_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='کارمند'),
        ),
    ]
