# Generated by Django 3.0.6 on 2021-03-13 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20210220_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('تومان', 'تومان'), ('ریال', 'ریال'), ('دلار', ' دلار'), ('یورو', 'یورو'), ('پوند', 'پوند'), ('دینار', 'دینار'), ('درهم', 'درهم'), ('افغانی', 'افغانی'), ('لیر', 'لیر'), ('مانات', 'مانات')], max_length=255, null=True, verbose_name='واحد پولی'),
        ),
        migrations.AlterField(
            model_name='enroll_invitation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyinvitations', to='common.Company', verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('عدد', 'عدد'), ('کیلوگرم', 'کیلوگرم'), ('گرم', ' گرم'), ('تن', 'تن'), ('بسته', 'بسته'), ('جعبه', 'جعبه'), ('کارتن', 'کارتن'), ('متر', 'متر'), ('لیتر', 'لیتر'), ('مترمکعب', 'مترکعب'), ('سی\u200cسی', 'سی\u200cسی'), ('مثقال', 'مثقال')], max_length=255, null=True, verbose_name='واحد اندازه\u200cگیری'),
        ),
    ]
