# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20210330_1929'),
        ('contacts', '0001_initial'),
        ('lead', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0001_initial'),
        ('deals', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('doc', models.FileField(default='', upload_to='docs', verbose_name='فایل')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_docs', to='accounts.Account', verbose_name='نام مشتری')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companydocs', to='common.Company', verbose_name='کاربر سایت')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_docs', to='contacts.Contact', verbose_name='نام شخص')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('deals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_docs', to='deals.Deal', verbose_name='عنوان معامله')),
                ('leads', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_docs', to='lead.Lead', verbose_name='عنوان سرنخ')),
                ('opportunities', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_docs', to='opportunity.Opportunity', verbose_name='عنوان فرصت')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_docs', to='tasks.Task', verbose_name='عنوان وظیفه')),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs_teams', to='teams.Teams', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
                'ordering': ['-created_on'],
            },
        ),
    ]
