# Generated by Django 3.0.6 on 2021-02-13 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0016_auto_20210211_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('target', models.IntegerField(blank=True, null=True, verbose_name='تعداد تارگت')),
                ('current', models.IntegerField(default=0, verbose_name='تعداد کنونی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytargets_staff', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_target_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'اهداف',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('target', models.IntegerField(blank=True, null=True, verbose_name='تعداد تارگت')),
                ('current', models.IntegerField(default=0, verbose_name='تعداد کنونی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytargets_company', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_target_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'هدف',
                'verbose_name_plural': 'اهداف',
                'ordering': ['-created_on'],
            },
        ),
    ]
