# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Targetsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companytargetsubjects', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetsubject_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': ' موضوع هدف',
                'verbose_name_plural': 'موضوعات  اهداف',
            },
        ),
        migrations.CreateModel(
            name='StaffTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('target_subject', models.CharField(choices=[('معاملات', 'معاملات'), ('سرنخ\u200cها', 'سرنخ\u200cها'), ('وظایف', 'وظایف'), ('فرصت\u200cها', 'فرصت\u200cها')], max_length=100, null=True, verbose_name='موضوع')),
                ('target', models.IntegerField(blank=True, null=True, verbose_name='تعداد تارگت')),
                ('current', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد کنونی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytargets_staff', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_target_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_staff', to='common.Enrolled', verbose_name='نام کارمند')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stafftargets_subject', to='targets.Targetsubject', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'هدف کارمند',
                'verbose_name_plural': 'اهداف کارمندان',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('target_subject', models.CharField(choices=[('معاملات', 'معاملات'), ('سرنخ\u200cها', 'سرنخ\u200cها'), ('وظایف', 'وظایف'), ('فرصت\u200cها', 'فرصت\u200cها')], max_length=100, null=True, verbose_name='موضوع')),
                ('target', models.IntegerField(blank=True, null=True, verbose_name='تعداد تارگت')),
                ('current', models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد کنونی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companytargets_company', to='common.Company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_target_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companytargets_subject', to='targets.Targetsubject', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'هدف شرکت',
                'verbose_name_plural': 'اهداف شرکت',
                'ordering': ['-created_on'],
            },
        ),
    ]
