# Generated by Django 3.0.6 on 2021-02-14 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0016_auto_20210211_1554'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Targetsubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companytargetsubjects', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targetsubject_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': ' موضوع هدف',
                'verbose_name_plural': 'موضوعات  هدف\u200cها',
            },
        ),
    ]
