# Generated by Django 3.0.6 on 2021-02-14 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('targets', '0002_targetsubject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytargets',
            options={'ordering': ['-created_on'], 'verbose_name': 'هدف شرکت', 'verbose_name_plural': 'اهداف شرکت'},
        ),
        migrations.AlterModelOptions(
            name='stafftargets',
            options={'ordering': ['-created_on'], 'verbose_name': 'هدف کارمند', 'verbose_name_plural': 'اهداف کارمندان'},
        ),
        migrations.AlterModelOptions(
            name='targetsubject',
            options={'verbose_name': ' موضوع هدف', 'verbose_name_plural': 'موضوعات  اهداف'},
        ),
        migrations.AddField(
            model_name='stafftargets',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_staff', to=settings.AUTH_USER_MODEL, verbose_name='نام کارمند'),
        ),
        migrations.AlterField(
            model_name='companytargets',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companytargets_subject', to='targets.Targetsubject', verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='stafftargets',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stafftargets_subject', to='targets.Targetsubject', verbose_name='موضوع'),
        ),
    ]
