# Generated by Django 3.0.6 on 2021-02-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20210214_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytargets',
            name='target_subject',
            field=models.CharField(choices=[('معاملات', 'معاملات'), ('سرنخ\u200cها', 'سرنخ\u200cها'), ('وظایف', 'وظایف'), ('فرصت\u200cها', 'فرصت\u200cها')], max_length=100, null=True, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='stafftargets',
            name='target_subject',
            field=models.CharField(choices=[('معاملات', 'معاملات'), ('سرنخ\u200cها', 'سرنخ\u200cها'), ('وظایف', 'وظایف'), ('فرصت\u200cها', 'فرصت\u200cها')], max_length=100, null=True, verbose_name='وضعیت'),
        ),
    ]
