# Generated by Django 3.0.6 on 2021-02-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_auto_20210214_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytargets',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companytargets_subject', to='targets.Targetsubject', verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='companytargets',
            name='target_subject',
            field=models.CharField(choices=[('معاملات', 'معاملات'), ('سرنخ\u200cها', 'سرنخ\u200cها'), ('وظایف', 'وظایف'), ('فرصت\u200cها', 'فرصت\u200cها')], max_length=100, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='stafftargets',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stafftargets_subject', to='targets.Targetsubject', verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='stafftargets',
            name='target_subject',
            field=models.CharField(choices=[('معاملات', 'معاملات'), ('سرنخ\u200cها', 'سرنخ\u200cها'), ('وظایف', 'وظایف'), ('فرصت\u200cها', 'فرصت\u200cها')], max_length=100, null=True, verbose_name='موضوع'),
        ),
    ]
