# Generated by Django 3.0.6 on 2021-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_auto_20210214_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytargets',
            name='current',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد کنونی'),
        ),
        migrations.AlterField(
            model_name='stafftargets',
            name='current',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد کنونی'),
        ),
    ]
