# Generated by Django 3.0.6 on 2021-03-30 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20210330_1929'),
        ('contacts', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpportunityStatus_number', models.IntegerField(verbose_name='شماره مرحله')),
                ('OpportunityStatus_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('won', models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و فرصت موفق است این تیک را بزنید.')),
                ('lost', models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و شکست در فرصت است این تیک را بزنید.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyopportunitystatus', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_status_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'مرحله فرصت',
                'verbose_name_plural': 'مراحل فرصت',
            },
        ),
        migrations.CreateModel(
            name='OpportunitySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OpportunitySource_title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companyopportunitysource', to='common.Company', verbose_name='کاربر سایت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_source_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ساخته شده توسط')),
            ],
            options={
                'verbose_name': 'منبع فرصت',
                'verbose_name_plural': 'منابع فرصت',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='عنوان')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='مبلغ')),
                ('probability', models.IntegerField(blank=True, default=0, null=True, verbose_name='احتمال')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('archive', models.BooleanField(default=False, verbose_name='بایگانی شود؟')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='accounts.Account', verbose_name='مشتری')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_assigned_to', to='common.Enrolled', verbose_name='محول شده به')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyopportunity', to='common.Company', verbose_name='کاربر سایت')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Contact', verbose_name='شخص')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunity_converted_by', to='common.Enrolled', verbose_name='تکمیل\u200cشده توسط')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunity_source', to='opportunity.OpportunitySource', verbose_name='منبع')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunity_status', to='opportunity.OpportunityStatus', verbose_name='مرحله')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tags', verbose_name='تگ\u200cها')),
                ('teams', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oppurtunity_teams', to='teams.Teams', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'فرصت',
                'verbose_name_plural': 'فرصت\u200cها',
                'ordering': ['-created_on'],
            },
        ),
    ]
