# Generated by Django 3.0.6 on 2021-02-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitystatus',
            name='lost',
            field=models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و شکست در فرصت است این تیک را بزنید.'),
        ),
        migrations.AddField(
            model_name='opportunitystatus',
            name='won',
            field=models.BooleanField(default=False, verbose_name='در صورتی که این مرحله بیانگر مرحله پایانی و فرصت موفق است این تیک را بزنید.'),
        ),
    ]
