# Generated by Django 3.0.6 on 2021-01-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'ordering': ['-created_on'], 'verbose_name': 'فرصت', 'verbose_name_plural': 'فرصت\u200cها'},
        ),
    ]
