# Generated by Django 3.0.6 on 2021-04-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='مبلغ'),
        ),
    ]
