# Generated by Django 3.0.6 on 2021-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210116_1353'),
        ('opportunity', '0002_auto_20210116_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=64, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.Tags', verbose_name='تگ\u200cها'),
        ),
    ]
