# Generated by Django 3.0.6 on 2021-02-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthday'),
        ('accounts', '0002_auto_20210201_1854'),
        ('common', '0013_auto_20210207_1343'),
        ('teams', '0002_teams_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunity', '0002_auto_20210208_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='accounts.Account', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='محول شده به'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companyopportunity', to='common.Company', verbose_name='کاربر سایت'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.Contact', verbose_name='شخص'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='converted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunity_converted_by', to=settings.AUTH_USER_MODEL, verbose_name='تکمیل\u200cشده توسط'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunity_source', to='opportunity.OpportunitySource', verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Opportunity_status', to='opportunity.OpportunityStatus', verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tags', verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oppurtunity_teams', to='teams.Teams', verbose_name='تیم'),
        ),
    ]
