# Generated by Django 3.0.6 on 2021-02-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0004_opportunity_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='closed_on',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='احتمال'),
        ),
    ]
